import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { createClient } from '@supabase/supabase-js';

const rootDir = process.cwd();
const envPath = path.join(rootDir, '.env');
const tfVarsPath = path.join(rootDir, 'terraform', 'terraform.tfvars');

console.log('🚀 Starting Turn-Key OCI Deployment Pipeline...');

// 1. Parse local .env file
if (!fs.existsSync(envPath)) {
  console.error('❌ Error: .env file not found in root directory.');
  process.exit(1);
}

const envContent = fs.readFileSync(envPath, 'utf-8');
const env: Record<string, string> = {};
envContent.split('\n').forEach(line => {
  const trimmed = line.trim();
  if (trimmed && !trimmed.startsWith('#') && trimmed.includes('=')) {
    const idx = trimmed.indexOf('=');
    const key = trimmed.substring(0, idx).trim();
    let val = trimmed.substring(idx + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.substring(1, val.length - 1);
    }
    env[key] = val;
  }
});

const supabaseUrl = env.SUPABASE_URL;
const supabaseKey = env.SUPABASE_KEY;

if (!supabaseUrl || !supabaseKey) {
  console.error('❌ Missing SUPABASE_URL or SUPABASE_KEY in .env file.');
  process.exit(1);
}

import { Client } from 'pg';

async function runMigration() {
  const pgUrl = env.SUPABASE_DATABASE_URL;
  const migrationSql = `
  ALTER TABLE public.pin_records
    ADD COLUMN IF NOT EXISTS payment_network VARCHAR(64) NOT NULL DEFAULT 'algorand:mainnet',
    ADD COLUMN IF NOT EXISTS tx_hash VARCHAR(128),
    ADD COLUMN IF NOT EXISTS token_address VARCHAR(128),
    ADD COLUMN IF NOT EXISTS payer_address VARCHAR(128),
    ADD COLUMN IF NOT EXISTS amount_paid NUMERIC(20, 0),
    ADD COLUMN IF NOT EXISTS settlement_status VARCHAR(32) DEFAULT 'SETTLED';

  CREATE UNIQUE INDEX IF NOT EXISTS idx_pin_records_chain_tx 
    ON public.pin_records(payment_network, tx_hash) 
    WHERE tx_hash IS NOT NULL;
  `;

  if (pgUrl) {
    try {
      console.log('Connecting via Postgres connection string to execute DDL schema migration...');
      const client = new Client({ connectionString: pgUrl, ssl: { rejectUnauthorized: false } });
      await client.connect();
      await client.query(migrationSql);
      await client.end();
      console.log('✅ Direct PostgreSQL schema migration executed successfully!');
      return;
    } catch (err: any) {
      console.warn('⚠️ Direct Postgres connection failed, checking REST endpoint:', err.message);
    }
  }

  const supabase = createClient(supabaseUrl, supabaseKey, { auth: { persistSession: false } });
  const { error } = await supabase.from('pin_records').select('cid').limit(1);
  if (error) {
    console.warn('⚠️ Supabase test query warning:', error.message);
  } else {
    console.log('✅ Connected to Supabase REST API endpoint.');
  }
}

// 3. Generate terraform.tfvars from .env
console.log('📝 Step 2: Auto-generating terraform/terraform.tfvars from .env...');

const tfVarsContent = `# Auto-generated by deploy pipeline
tenancy_ocid          = "${env.OCI_TENANCY_OCID || 'ocid1.tenancy.oc1..example...'}"
user_ocid             = "${env.OCI_USER_OCID || 'ocid1.user.oc1..example...'}"
fingerprint           = "${env.OCI_FINGERPRINT || 'xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx'}"
private_key_path      = "${env.OCI_PRIVATE_KEY_PATH || '~/.oci/oci_api_key.pem'}"
region                = "${env.OCI_REGION || 'us-ashburn-1'}"
compartment_ocid      = "${env.OCI_COMPARTMENT_OCID || 'ocid1.compartment.oc1..example...'}"
ssh_public_key        = "${env.OCI_SSH_PUBLIC_KEY || 'ssh-rsa AAAAB3NzaC1yc2E...'}"

pinata_jwt            = "${env.PINATA_JWT || ''}"
supabase_url          = "${env.SUPABASE_URL || ''}"
supabase_key          = "${env.SUPABASE_KEY || ''}"
duckdns_subdomain     = "${env.DUCKDNS_SUBDOMAIN || 'pay-to-pin'}"
duckdns_token         = "${env.DUCKDNS_TOKEN || ''}"
escrow_address        = "${env.ESCROW_ADDRESS || 'W5IRXJWPSXNUJVSN2MOEJGTDGKUGFKUDVPTR5ZQVMDG5O4KYD5M3QPG3TE'}"
evm_escrow_address    = "${env.EVM_ESCROW_ADDRESS || '0x0000000000000000000000000000000000000000'}"
solana_escrow_address = "${env.SOLANA_ESCROW_ADDRESS || '11111111111111111111111111111111'}"
notification_email    = "${env.NOTIFICATION_EMAIL || 'garretparker@gmail.com'}"
`;

fs.writeFileSync(tfVarsPath, tfVarsContent);
console.log('✅ Saved terraform/terraform.tfvars.');

// 4. Run Terraform Apply
console.log('🏗️ Step 3: Executing Terraform deployment...');
try {
  runMigration().then(() => {
    const tfDir = path.join(rootDir, 'terraform');
    console.log('Initializing Terraform...');
    execSync('terraform init', { cwd: tfDir, stdio: 'inherit' });
    console.log('Applying Terraform Plan...');
    execSync('terraform apply -auto-approve', { cwd: tfDir, stdio: 'inherit' });
    console.log('🎉 TURN-KEY DEPLOYMENT COMPLETE! Gateway live on OCI.');
  }).catch(err => {
    console.error('❌ Migration error:', err);
  });
} catch (err: any) {
  console.error('❌ Terraform deployment failed:', err.message);
  process.exit(1);
}
